### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by hacker1024** [UtsavisGreat/android_kernel_xiaomi_sm8150#1]
Hi. I'm hacker1024 on Telegram.
I'm getting no audio when compiling the `lineage-16.0` branch in my ROM.
Here's a log of when the microphone was attempted to be used, it's very similar for output too.
https://hastebin.com/zuyoyacife.txt

**Comment by UtsavBalar1231** [comment]
God bless Havoc and God Bless you.
